### ISSUE TITLE
Asociación has_many :through

### ISSUE THREAD

**Issue by tommyefr** [IIC2143-2016-2/syllabus#10]
Para el projecto de las bicletas tenemos un modelo User y un modelo Group. En nuestro planteamiento, por un lado, queremos que cada grupo pueda tener varios usuarios y cada usuario pueda tener varios grupos. Por otro lado, cada grupo puede tener uno o varios admins que en verdad son usuarios.

La idea es unir Gruop y User mediante has_many :through, que utiliza un modelo cómo intermediario,  en donde la tabla de unión (que es la que corresponde al modelo intermediario) contenga el id de ambos y un booleano que representa si es admin de grupo o no.  

A continuación los modelos de User y Group  y el posible modelo de intermediario

```ruby
class Group < ApplicationRecord
  has_many :intermediarios
  has_many :users, through: :intermediarios
end
 
class Intermediario < ApplicationRecord
  belongs_to :user
  belongs_to :group
end
 
class User < ApplicationRecord
  has_many :intermediarios
  has_many :groups, through: :intermediarios
end
```

- ¿Es necesario que esta tabla intermedia tenga un modelo correspondiente o puede ser solo una tabla? La duda recae en que el modelo intermediario no tiene ningun sentido mas que unir grupos con sus miembros (admin o no admin), por lo que no representa ningun tipo de dato abstracto como User o Group

- Cualquiera sea la respuesta a la pregunta anterior. Si , por ejemplo, quiero obtener todos los admins de un grupo, ¿Como accedo solo a los admins indicando que el booleano tenga el valor true (para admin)? 

- ¿Estoy pensando bien la solución o es otra la herramienta que debo usar para realizar una buena práctica?

**Comment by enaguero** [comment]
Con la resolución de la ayundantía:

```ruby
@group = Group.first
@users = User.joins(:intermediarios).where(intermediarios:{admin:true,group_id:@group.id})
```
