### ISSUE TITLE
Almacenacion y preguntas de significado

### ISSUE THREAD

**Issue by isipalma** [IIC2143-2016-2/syllabus#11]
Buenas!

Tenia una duda existencial sobre lo siguiente:
Para mis cuentas hago new en current_account.reports.new(blah) por lo que yo entendi se guarda la instancia en el modelo Report pero tambien se asocia la cuenta (report) a la cuenta de usuario pues mantiene una relacion has_many belong_to. Mi duda es el cómo se guardan las instancias en el atributo reports de current_account, pues en el index de reportes si le paso current_account.reports entrega una lista de los reportes asociados a esa cuenta.

Esta duda surge porque al intentar hacer una transaccion trato de encontrar el reporte del usuario con find_by(:name parems[:cuenta]) donde :cuenta seria el nombre de la cuenta en la que se quiere guardar las transaccion pero me entrega un nil

Saludos!

**Comment by enaguero** [comment]
```ruby
@user_accounts = current_user.accounts
```

**Comment by enaguero** [comment]
Visto en ayudantía.
