### ISSUE TITLE
Sportcialize horario

### ISSUE THREAD

**Issue by jedelacarrera** [IIC2143-2016-2/syllabus#12]
A mi grupo le tocó el tema de sportcialize y no tenemos muy claro como hacer el tema de los horarios disponibles. Pordría ser un modelo, pero quer atributos o métodos podrían implementarse?

**Comment by jedelacarrera** [comment]
Una de las ideas que tenemos (con ayuda del ayudante) es crear un modelo semana, un modelo dia y uno modulo (hora), por lo que cada semana tiene dias y cada dia modulos en que se debe permitir determinar los modulos en que el usuario está disponible. El problema es que serían muchos models y es más complicado.

La otra idea es que cada usuario tenga muchos módulos directamente y tiene que determinar cuales tiene disponibles y cuales no.

Que idea parece más sencilla y útil de implementar? Hay alguna otra forma mejor de hacerlo?

**Comment by Mapuentes** [comment]
Nosotros teniamos el mismo problema, pero lo que hicimos es crear una tabla timetable con 3 atributos id_usuario, dia y modulo , entonces lo que hacemos por ejemplo si un usuario tiene disponible el lunes modulo 1y  2, existen 2 instancias en la tabla con id_usuario, L,1 y otro id_usuario,L,2. Entonces cuando se cree el horario haga un match entre el usuario y el horario y si no lo encuentra lo considera no disponible. No se si se entiende ?

**Comment by enaguero** [comment]
@jedelacarrera me parece un buen approach el que usan @Mapuentes !
