### ISSUE TITLE
Problema al instalar gemas

### ISSUE THREAD

**Issue by jtagle2** [IIC2143-2016-2/syllabus#13]
Tengo un problema con el comando gem install. La semana pasada me estaba funcionando perfect, y ahora a nuestro proyecto le agregamos una nueva gema, y al correr el bundle install me tiraba un error de los certificate. Traté de arreglarlo con todas las soluciones que encontré en internet. En verdad todo me redirigía a [esta](https://gist.github.com/luislavena/f064211759ee0f806c88) issue. Hice lo que decía (supongo que lo hice bien), y no me funcionó, y al final ya me rendí y decidí partir de 0, es decir, desinstalar ruby y rails, e instalar todo de nuevo (fijándome tener la misma versión en todo a mi compañero de grupo, que a él si le funciona). El problema, es que instalé ruby desde 0, y me sigue tirando el mismo error.
![error](https://cloud.githubusercontent.com/assets/6934080/19198737/0c2e15ae-8c97-11e6-940f-35f1190fc80f.png)

¿Alguna idea de lo que puede ser?

Edit: Es en Windows 7

**Comment by enaguero** [comment]
@jtagle2 era muy extraño el problema hasta que mencionaste que trabajas en Windows. Lo más probable que sea eso :).
