### ISSUE TITLE
Gema groupdate

### ISSUE THREAD

**Issue by icrocco** [IIC2143-2016-2/syllabus#14]
¡Hola!
¿Es válido usar la gema groupdate? [https://github.com/ankane/groupdate](url)

Si es así ¿no hay problema con que no usemos sqlite como base de datos?

¡Gracias!

**Comment by enaguero** [comment]
@icrocco no, no hay problema en que la ocupen. Eso sí tendrán que realizar los test de los métodos que hagan para las próxima entrega :).

Saludos.
