### ISSUE TITLE
Duda entrega1

### ISSUE THREAD

**Issue by noksenberg** [IIC2143-2016-2/syllabus#16]
No me queda claro hasta que punto hay que desarrollar la aplicación. CanCanCan tiene que hacer manejo de permisos sobre que features? Lo decidimos nosotros, o ya tienen que estar implementadas todas las funcionalidades que se describían en la entrega0?

Gracias

**Comment by enaguero** [comment]
@noksenberg como marco de referencia tiene que:

- Identificar los diferentes tipos de roles.
- Mostrar la vista correspondiente a cada usuario.

Por ahora con eso basta, ahora si logran implementar los permisos para las funcionalidades con el ProductOwner, aún mejor. Tendrán menos trabajo para la siguiente entrega donde solicitaré todos los permisos 👍 . 

Espero que sirva la aclaración.

Saludos.
