### ISSUE TITLE
Problema con devise

### ISSUE THREAD

**Issue by noksenberg** [IIC2143-2016-2/syllabus#17]
Hola, tengo el siguiente problema con Devise, tras hacer el Sign Up de un nuevo usuario, se crea el nuevo objeto usuario, pero todos los campos que se pueden rellenar quedan con nils. Alguna idea?

Gracias

**Comment by josemontesp** [comment]
Lo que pasa es que el controller que maneja un nuevo registro de devise por defecto no permite parámetros extra. Para agregar parámetros como por ejemplo first_name y last_name tienes que modificar el archivo controllers/users/registrations_controller.rb

Debería quedar algo así:
```
  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone])
  end
```

**Comment by noksenberg** [comment]
La carpeta es RailsApp! Ya tengo ese código, está en application_controller.rb
Es algo así (está en la documentación de devise):

`class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:username, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password)}
  end
end`

**Comment by enaguero** [comment]
@josemontesp y @noksenberg , buenos aportes! 

Thanks!

**Comment by noksenberg** [comment]
Me refiero a que aún con eso no funciona!
