### ISSUE TITLE
belongs to one or another model

### ISSUE THREAD

**Issue by josemontesp** [IIC2143-2016-2/syllabus#19]
Tengo los modelos Comment, Post y Place. Un post puede tener comentarios y un lugar también.

```
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
    belongs_to :place
end
```
```
class Place < ApplicationRecord
	has_many :comments
end
```
```
class Post < ApplicationRecord
	has_many :comments
end
```

El problema es que cuando quiero crear un comentario rails me obliga a que pertenezca a un lugar y a un post simultáneamente.

¿Hay alguna forma de hacer que un comentario pertenezca a un lugar xor post?

**Comment by josemontesp** [comment]
Me auto-respondo:

[http://culttt.com/2016/01/13/creating-polymorphic-relationships-in-ruby-on-rails/](url)

**Comment by enaguero** [comment]
@josemontesp te dejo esta referencia por si te interesa más el tema:

https://launchschool.com/blog/understanding-polymorphic-associations-in-rails

Felicidades por la motivación !
