### ISSUE TITLE
Aprendiendo Ruby 

### ISSUE THREAD

**Issue by nigfasa** [IIC2143-2016-2/syllabus#2]
Recuerdo que en la ayudantía se hablo para una pagina muy buena para aprender ruby, pero no recuerdo cual es. Creo que no esta entre las que se encuentran en el siding, y que alguien preguntó si era mejor que la codeacademy. 

Alguien sabe cual es?

**Comment by FernandoPieressa** [comment]
La pagina que recomendaron en la ayudantia para aprender ruby era

http://rubykoans.com/

**Comment by nigfasa** [comment]
Que grande Fernando! Freddie agradece igual!
