### ISSUE TITLE
Javascript no carga en show

### ISSUE THREAD

**Issue by tamycova** [IIC2143-2016-2/syllabus#21]
Hola!!

Dejo esta issue por si alguien se encuentra con este problema.  Lo que pasa es que Rails usa Turbolinks para hacer más eficiente el cargar la página y solo compila los .css y .js una vez, entonces (document).ready solo va a funcionar cuando se recargue la página, no cuando se ingrese a través de un enlace dentro de ella. 

Para que se "triggeree"  el .js hay que usar turbolinks events y las respuestas de stackoverflow estan out of date, los nombres de los eventos de turbolink cambiaron en su nueva versión: https://github.com/turbolinks/turbolinks/issues/9.

Cheers

**Comment by enaguero** [comment]
@tamycova , te adjunto una solución al problema.

http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links

Espero que te sirva.

Saludos.

**Comment by tamycova** [comment]
Gracias @enaguero ! Ya lo había solucionado, la solución es el edit dos de esa respuesta (por el cambio de nombre de los eventos, ahora es 'turbolinks:load').
Saludos!
