### ISSUE TITLE
Exportar gráficos

### ISSUE THREAD

**Issue by ifcarrera** [IIC2143-2016-2/syllabus#25]
Hola, tengo la siguiente duda. Una de nuestras funcionalidades del proyecto es que se puedan exportar (descargar) los gráficos que les mostramos al usuario; la duda es si al exportarse es NECESARIO que se descarguen como Excel o podría ser algo como una imagen y descargarse como .png?
Saludos

**Comment by enaguero** [comment]
@ifcarrera , ¿en qué proyecto estas? Dado que no soy tu ProductOwner no conozco todas las especificaciones solicitadas. Si describes mejor lo que tienes que implementar, te puedo guiar a nivel de código.
