### ISSUE TITLE
Buenas practicas en Git y en MVC

### ISSUE THREAD

**Issue by jicortes2** [IIC2143-2016-2/syllabus#26]
Hola! Ya terminando el curso quería aprovechar de consultar sobre algunas practicas de git y mcv que no tengo muy claro

- La de git es solo por curiosidad, pero hay una recomendación de cuando borrar las branches? Como al final de un sprint, una vez que termine de trabajar en esa área u otro momento? 

- En MVC, que cosas se recomienda agregarlos en el controlador y cuales en el modelo? Que en mi proyecto tengo la mayor parte (si es que no todo) el código en los controladores.

Gracias!!

**Comment by jnavon** [comment]
No hay necesidad de borrar branches o al menos apurarse en hacerlo.

En cuanto a MVC lo discutimos en clase.  El código del controlador actúa intermediando con el modelo y la vista solamente.  En ningún caso debe contener lógica de dominio (o reglas de negocio),  validaciones, etc.

**Comment by jicortes2** [comment]
Si, ahora recuerdo haberlo pasado, solo que en ese momento no lo entendí porque no habia tenido la experiencia aun con MVC. Muchas gracias!
