### ISSUE TITLE
Modelo y relaciones

### ISSUE THREAD

**Issue by tamycova** [IIC2143-2016-2/syllabus#3]
Hola, tengo unas dudas. Hice mi modelo como lo haría para una base de datos relacional, pero tengo algunos problemas al pensarlo en asociaciones de rails. 

1. Cuando tengo una relación simple, por ejemplo (en mayúscula entidades), USUARIO -> pertenece -> GRUPO, usando has_one, has_many queda bien representado? qué pasa si pertenece tiene atributos?
2. Si la relación es múltiple, por ejemplo USUARIO->publica-> POST ->COMENTARIO (post y comentario salen de publica), la única opción que veo en rails es has_one :through, pero no sé si representa a cabalidad la relación.
3. Finalmente la herencia, por ejemplo POST isA Publicación y LUGAR isA Publicación, no veo una asociación en rails que me permita hacerlo en el modelo. Hay una mejor forma o lo hago a mano?

En realidad son dudas muy simples, enfocadas más a que no entiendo como rails maneja las relaciones entre modelos.

**Comment by enaguero** [comment]
@tamycova: Te respondo por punto

(1) Te recomiendo ver http://guides.rubyonrails.org/association_basics.html en la descripción belongs_to y has_one. Ahí encontrarás la diferencia que creo que andas buscando. 

Para describir una relación en ER debes usar las siguientes palabras: 
- one to one.
- one to many.
- many to many. 

https://en.wikipedia.org/wiki/One-to-many_(data_model)

Así te podré entender mejor :). Si tienes un modelo en rails puedes tener todos los atributos que desees.

(2) :through se ocupa sólo con modelos de relaciones many to many :( , no entiendo como pudiste llegar a esa conclusión con has_one. Lee de nuevo la referencia , en particular : Choosing Between has_many :through and has_and_belongs_to_many.

(3) La herencia en base de dato se puede hacer de varias formas:

(a) Crear un modelo Publication que tenga un type, luego crear una constante en el modelo que sea un arreglo que tenga lo tipos de publicaciones que tienes 👍 . Ahora bien, si tienen uno tiene más atributos que otro, simplemente crear dos modelos diferentes.

**Comment by enaguero** [comment]
@tamycova , ¿pudiste revisar las referencias que dejé? Dejaré abierto hasta el final del sprint 01 este issue.

**Comment by tamycova** [comment]
@enaguero puntos 1 y 2 los analizaré y te respondo mañana (ya había leído esas refs pero parece que me apresure mucho con la issue). Respecto al punto 3, al final decidimos usar STI con --parent, lo único "penca" es que la herencia no se ve reflejada en erd, y creo que igual es importante tenerla en el modelo, asique mejor quizás hagamos dos modelos independientes o photoshopear a la mala la herencia en el modelo jaja

**Comment by enaguero** [comment]
@tamycova te recomiendo usar dos modelos. Es rápido y sigue cumpliendo los requerimientos solicitados. 

Saludos.
