### ISSUE TITLE
Trabajo en grupo Github

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2143-2016-2/syllabus#4]
Hola! Queria saber si habia una forma eficiente de trabajar en grupo en github cuando vamos a editar los mismos archivos, puesto que aunque trabajemos en distintos branches, va a tirar problemas cuando intentemos hacer merge, o sobreescribira los archivos. O la forma mas eficiente seria que cada uno trabaje en distintos modulos solamente para no tener problemas?

**Comment by enaguero** [comment]
@FernandoPieressa lo que me preguntas se hace resolviendo conflictos. Te dejo la siguiente referencia:

https://githowto.com/resolving_conflicts

No deberían tener mayores problemas :).
