### ISSUE TITLE
Recursos compartidos HTML

### ISSUE THREAD

**Issue by FernandoPieressa** [IIC2143-2016-2/syllabus#6]
Hola! Tengo una duda respecto a como guardar los recursos compartidos que usan mis HTML con bootstrap en ruby on rails, puesto que como rails te crea varios archivos, con muchas views y css respectivos para cada uno, no se como eficientemente dejar que todas las views consigan recursos de los mismos archivos. (Imagenes, .js, .css, etc..)

Estos son algunos de las carpetas que quiero que todos tengan acceso
![screenshot from 2016-09-27 18-46-12](https://cloud.githubusercontent.com/assets/13782155/18992622/bb31df10-86f5-11e6-9574-d97646520baf.png)

**Comment by enaguero** [comment]
@FernandoPieressa los recursos compartidos que mencionas algunos se pueden integrar de formas diferentes. Como primera cosa te recomiendo leer [The Asset Pipeline](http://guides.rubyonrails.org/asset_pipeline.html) donde se describe como Rails organiza los archivos js y css para cada controlador y para que estén disponibles para todos. 

Con respecto a algunas cosas que mencionas y veo en tu descripción:

(1) Fonts: 
- http://stackoverflow.com/questions/12329137/how-to-add-a-custom-font-to-rails-app
- https://gist.github.com/anotheruiguy/7379570

(2) Font awesome : Usa la [gema](https://github.com/bokmann/font-awesome-rails), no pierdas tiempo.

(3) Imágenes: Estarán disponibles si las dejas debajo de la carpeta img. En rails está el helper asset_path para acceder a esos recursos.
http://apidock.com/rails/ActionView/Helpers/AssetUrlHelper/asset_path

Existen otros, te recomiendos buscarlos :).

(4) Scripts ? ¿Qué tipo de scripts quieres usar?  Para usar ruby scripts :), podrías considerar esto:

http://stackoverflow.com/questions/14912055/how-to-include-custom-rb-script-in-rails-app

Te recomiendo hacer preguntas más específicas. Tu duda es demasiado general y no es posible ponerse en todos los casos que hayas probado.

Saludos.
