### ISSUE TITLE
Usuarios y Admins

### ISSUE THREAD

**Issue by gantunesr** [IIC2143-2016-2/syllabus#7]
Hola! No entiendo muy bien como hacemos la diferenciación entre el registro de usuarios y admins en la aplicación. ¿Los admins vienen predeterminados o hay que reconocerlos por el email que usan para registrarse?

**Comment by ifcarrera** [comment]
Por lo que nos dijo Erwin, los admin tienen que ser reconocidos por el mail con el que ingresen al sitio.

**Comment by enaguero** [comment]
@gantunesr en la aplicaciones por ahora no debería hacerse diferencia entre registro de los usuarios admin. En efecto, el registro es sólo para usuarios normales, los usuarios administradores tienen que ser creados por otro administrador que viene por defecto, por ejemplo, un usuario creado en el archivo seed. 

Ahora ten cuidado que en el registro si tienes un campo "role" o "type" que no te lo pregunto ya que un usuario cualquier sería administrador del sitio, lo cual no es deseable.
