### ISSUE TITLE
Asociaciones entre modelos

### ISSUE THREAD

**Issue by isipalma** [IIC2143-2016-2/syllabus#8]
Hola!

Llevo un buen rato buscando por google como hacer las relaciones entre transacciones y usuarios, y entre usuarios y cuentas, sin embargo aun no logro que en el index se muestren solamente las transacciones del usuario conectado. Ya agregue el belong_to y el has_many, y he cambiado los migrate.
He intentado esto:

def index
    @accounts = Account.find_by_id(id)
    @accounts.transactions
  end

pero no entiendo muy bien como funcniona el comando Account.find_by_id(id)

Tambien, al crear una transaccion me pide que agregue una cuenta existente (ya que a transaccion le puse una llave foranea report_id (report son las cuentas)) pero no se como decirle al programa (en el controlador de transacciones, en la funcion create) que revise si esta la cuenta y la agregue a sus atributos, intente esto:

@reports = Report.find(params[:id])
@reports = current_user.reports.find(params[:id])

pero despues no se como hacer la transaccion (new)

Saludos!

**Comment by enaguero** [comment]
@isipalma trata de hacer sólo un problema por issue así puedo llevar mejor la discusión. Los tipos de asociaciones que puedes hacer son varios, a modo general, se me viene a la mente esto:

(1) Un usuario tiene muchas transacciones y una transacción tiene un sólo usuario :). Por lo que el id del usuario debería estar en el modelo transacción. 

(2) Ten presente que digamos que hay dos tipos de cuenta :O , las por defecto y las que el propio usuario crea. Por lo que podría hacer una diferencia en esto a nivel de modelo ya que las cuenta por defecto las pueden tener todos los usuarios y las otras , sólo aquel usuario que las crea :). 

(a) Podrías crear un modelo llamado cuentas del sistema o cuentas por defecto (ojo que nombre las cosas en inglés). Estas encuestas serían many to many con todos los usuarios.

(b) Las cuentas que crea un usuario son has_many y belongs tú, un usuario tienen muchas cuentas creadas por él 👍 .

Espero que te sirva.

**Comment by enaguero** [comment]
@isipalma ¿cómo te fue con esto? :octocat:

**Comment by isipalma** [comment]
Hola!

La verdad es que todo eso ya lo habia hecho, si mi problema era que no sabia de donde sacar las referencias de los objetos ni donde debia guardarlas (donde se guardaban las transacciones de un usuario) pero ya lo pude hacer

Muchas gracias igualmente ;)

Saludos
